# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a324bf25359e883da11b1d3d2f0bea066533ac59ab8371c4825efdd63cc771328bd64f1efaf161888b30e859892b9d49ff1f24c4ac4a4d086f7b617fd3965ec3

test:
  secret_key_base: 5b7ef7248bac72491bafad4fb5fe14bf11dcd17785bd50f6c7259c9a2363eddc366ebf7020e6f2d90536feee5e1ef816c693f176354a4a4ddf61e8f70cca3a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
